use rumqttc::{MqttOptions, Transport, TlsConfiguration};

use std::time::Duration;




let mut mqttoptions = MqttOptions::new("agrisentry_gateway", "j6b19636.ala.us-east-1.emqxsl.com", 8883);





mqttoptions.set_credentials("arleujr", "jaqueline101010");




mqttoptions.set_transport(Transport::Tls(TlsConfiguration::default()));




mqttoptions.set_keep_alive(Duration::from_secs(45));

mqttoptions.set_clean_session(true);


