# Porta 1883: Canal TCP tradicional para o seu Gateway em Rust conversar na rede privada
listener 1883
allow_anonymous true


# Porta 8080: Canal HTTP/WebSockets para passar no Health Check do Render e manter o serviço LIVE
listener 8080
protocol websockets
allow_anonymous true


# Diretrizes de persistência e logs operacionais
persistence true
persistence_location /mosquitto/data/
log_dest stdout
